plugins {
    id 'com.android.application'
}

android {
    namespace 'com.soyunomas.pdflimpio'
    compileSdk 36

    defaultConfig {
        applicationId 'com.soyunomas.pdflimpio'
        minSdk 28
        targetSdk 36
        versionCode 2
        versionName '1.1.0'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'androidx.pdf:pdf-viewer-fragment:1.0.0-beta01'
}
