(() => {
'use strict';
const state={rawText:'',entities:[],counters:{PERSONA:0,EMPRESA:0,UBICACION:0,SECRETO:0},mode:'edit',currentSelection:'',searchQuery:'',searchMatches:[],activeMatchIndex:-1,indexOpen:false,lastFocused:null};
const labels={PERSONA:'Persona',EMPRESA:'Empresa',UBICACION:'Lugar',SECRETO:'Dato crítico'};
const ids=['entityCountTab','rawEditor','visualEditor','btnEditMode','btnMarkMode','modeHint','selectionBar','selectionText','searchRow','searchInput','btnClearSearch','searchStatus','btnPrevMatch','btnNextMatch','btnToggleIndex','indexPane','btnCloseIndex','indexList','workbench','protectStatus','btnGenerate','btnPaste','btnReset','registryBody','aiAnswer','btnRestore','restoredOutput','btnCopyRestored','restoreStatus','restoreEntityCount','promptModal','btnCloseModal','anonymizedOutput','modalSummary','btnCopyPrompt','btnGoRestore','toast'];
const dom=Object.fromEntries(ids.map(id=>[id,document.getElementById(id)]));
const escapeRegExp=t=>t.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');
const isWord=c=>c?/\p{L}|\p{N}|_/u.test(c):false;
const entityRegex=(text,flags='giu')=>new RegExp(`${isWord(text[0])?'(?<![\\p{L}\\p{N}_])':''}${escapeRegExp(text)}${isWord(text.at(-1))?'(?![\\p{L}\\p{N}_])':''}`,flags);
const overlap=(a,b,c,d)=>a<d&&b>c;
function toast(msg){dom.toast.textContent=msg;dom.toast.hidden=false;clearTimeout(toast.t);toast.t=setTimeout(()=>dom.toast.hidden=true,2400)}
function status(el,msg,tone=''){el.className=`status-line${tone?` ${tone}`:''}`;el.innerHTML=msg}
function setPanel(name){document.querySelectorAll('[role="tabpanel"]').forEach(p=>p.hidden=true);document.querySelectorAll('.tab').forEach(t=>t.setAttribute('aria-selected','false'));const panel=document.getElementById(`panel-${name}`),tab=document.querySelector(`.tab[data-panel="${name}"]`);panel.hidden=false;tab.setAttribute('aria-selected','true');tab.focus({preventScroll:true})}
document.querySelector('.tabs').addEventListener('click',e=>{const t=e.target.closest('.tab[data-panel]');if(t)setPanel(t.dataset.panel)});
document.querySelector('.tabs').addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;const tabs=[...document.querySelectorAll('.tab')],i=tabs.indexOf(document.activeElement);if(i<0)return;e.preventDefault();let n=i;if(e.key==='ArrowLeft')n=(i-1+tabs.length)%tabs.length;if(e.key==='ArrowRight')n=(i+1)%tabs.length;if(e.key==='Home')n=0;if(e.key==='End')n=tabs.length-1;tabs[n].click()});
function sync(){state.rawText=dom.rawEditor.value;updateAction()}
function setMode(mode){if(mode===state.mode)return;if(mode==='mark')sync();state.mode=mode;const edit=mode==='edit';dom.rawEditor.hidden=!edit;dom.visualEditor.hidden=edit;dom.searchRow.hidden=edit;dom.btnEditMode.setAttribute('aria-pressed',String(edit));dom.btnMarkMode.setAttribute('aria-pressed',String(!edit));dom.modeHint.textContent=edit?'Pega con Ctrl+V o escribe directamente.':'Selecciona un fragmento o búscalo para proteger todas sus apariciones.';dom.selectionBar.hidden=true;state.currentSelection='';if(edit){closeIndex();dom.rawEditor.focus()}else{renderVisual();dom.visualEditor.focus()}}
dom.btnEditMode.onclick=()=>setMode('edit');dom.btnMarkMode.onclick=()=>setMode('mark');dom.rawEditor.addEventListener('input',sync);
function entitySpans(){const spans=[];for(const entity of [...state.entities].sort((a,b)=>b.original.length-a.original.length)){const re=entityRegex(entity.original);let m;while((m=re.exec(state.rawText))){const start=m.index,end=start+m[0].length;if(!spans.some(s=>overlap(start,end,s.start,s.end)))spans.push({type:'entity',start,end,text:m[0],entity})}}return spans.sort((a,b)=>a.start-b.start)}
function computeSearch(spans){state.searchMatches=[];const q=state.searchQuery.trim();if(!q||!state.rawText){state.activeMatchIndex=-1;return}const re=new RegExp(escapeRegExp(q),'giu');let m;while((m=re.exec(state.rawText))){const start=m.index,end=start+m[0].length;if(!spans.some(s=>overlap(start,end,s.start,s.end)))state.searchMatches.push({index:state.searchMatches.length,start,end,expandedStart:start,expandedEnd:end,text:m[0]});if(!m[0].length)re.lastIndex++}if(!state.searchMatches.length)state.activeMatchIndex=-1;else if(state.activeMatchIndex<0||state.activeMatchIndex>=state.searchMatches.length)state.activeMatchIndex=0}
function renderVisual(){dom.visualEditor.replaceChildren();if(!state.rawText.trim()){dom.visualEditor.classList.add('empty');dom.visualEditor.textContent='No hay texto. Vuelve a Editar y pega o escribe el contenido.';state.searchMatches=[];updateSearch();renderIndex();return}dom.visualEditor.classList.remove('empty');const spans=entitySpans();computeSearch(spans);const tokens=[...spans,...state.searchMatches.map(m=>({type:'search',start:m.start,end:m.end,text:m.text,index:m.index}))].sort((a,b)=>a.start-b.start);let cursor=0;for(const token of tokens){if(token.start<cursor)continue;if(token.start>cursor)dom.visualEditor.append(document.createTextNode(state.rawText.slice(cursor,token.start)));if(token.type==='entity'){const mark=document.createElement('span');mark.className=`entity-mark entity-${token.entity.type.toLowerCase()}`;mark.textContent=token.text;mark.dataset.token=token.entity.token;mark.dataset.entityId=token.entity.id;mark.tabIndex=0;mark.setAttribute('role','button');mark.setAttribute('aria-label',`${token.text}, protegido como ${token.entity.token}. Pulsa para quitar.`);dom.visualEditor.append(mark)}else{const mark=document.createElement('mark');mark.className=`search-mark${token.index===state.activeMatchIndex?' active':''}`;mark.textContent=token.text;mark.dataset.searchIndex=token.index;dom.visualEditor.append(mark)}cursor=token.end}if(cursor<state.rawText.length)dom.visualEditor.append(document.createTextNode(state.rawText.slice(cursor)));updateSearch();renderIndex();requestAnimationFrame(focusMatch)}
function updateSearch(){const n=state.searchMatches.length;dom.searchStatus.textContent=!state.searchQuery.trim()?'Sin búsqueda':!n?'0 coincidencias':`${state.activeMatchIndex+1} de ${n}`;dom.btnPrevMatch.disabled=state.activeMatchIndex<=0;dom.btnNextMatch.disabled=state.activeMatchIndex<0||state.activeMatchIndex>=n-1}
function focusMatch(){dom.visualEditor.querySelectorAll('.search-mark').forEach(x=>x.classList.remove('active'));dom.indexList.querySelectorAll('.match-row').forEach(x=>x.classList.remove('active'));if(state.activeMatchIndex<0)return;const mark=dom.visualEditor.querySelector(`[data-search-index="${state.activeMatchIndex}"]`),row=dom.indexList.querySelector(`[data-match-index="${state.activeMatchIndex}"]`);if(mark){mark.classList.add('active');mark.scrollIntoView({block:'center',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'})}if(row){row.classList.add('active');if(state.indexOpen)row.scrollIntoView({block:'nearest'})}updateSearch()}
function openIndex(){state.indexOpen=true;dom.indexPane.hidden=false;dom.workbench.classList.add('with-index');dom.btnToggleIndex.setAttribute('aria-expanded','true');dom.btnToggleIndex.textContent='Ocultar contexto';renderIndex()}
function closeIndex(){state.indexOpen=false;dom.indexPane.hidden=true;dom.workbench.classList.remove('with-index');dom.btnToggleIndex.setAttribute('aria-expanded','false');dom.btnToggleIndex.textContent='Ver contexto'}
dom.btnToggleIndex.onclick=()=>state.indexOpen?closeIndex():openIndex();dom.btnCloseIndex.onclick=closeIndex;
function renderIndex(){dom.indexList.replaceChildren();if(!state.searchQuery.trim()||!state.searchMatches.length){const p=document.createElement('p');p.className='index-empty';p.textContent=state.searchQuery.trim()?'No quedan coincidencias sin proteger.':'Busca un término para ver sus apariciones.';dom.indexList.append(p);return}for(const m of state.searchMatches){const row=document.createElement('article');row.className=`match-row${m.index===state.activeMatchIndex?' active':''}`;row.dataset.matchIndex=m.index;const meta=document.createElement('div');meta.className='match-meta';const num=document.createElement('span');num.className='match-number';num.textContent=`Aparición ${m.index+1}`;const see=document.createElement('button');see.type='button';see.className='btn btn-small';see.dataset.action='focus';see.textContent='Ver';meta.append(num,see);const sn=document.createElement('p');sn.className='snippet';const a=Math.max(0,m.start-44),b=Math.min(state.rawText.length,m.end+44);sn.append(document.createTextNode((a?'…':'')+state.rawText.slice(a,m.start)));const hi=document.createElement('mark');hi.textContent=m.text;sn.append(hi,document.createTextNode(state.rawText.slice(m.end,b)+(b<state.rawText.length?'…':'')));const exp=document.createElement('div');exp.className='expand-controls';for(const [dir,label] of [['left','← palabra'],['input',''],['right','palabra →']]){if(dir==='input'){const input=document.createElement('input');input.value=state.rawText.slice(m.expandedStart,m.expandedEnd);input.dataset.role='expanded';input.setAttribute('aria-label','Fragmento exacto a proteger');exp.append(input)}else{const btn=document.createElement('button');btn.type='button';btn.className='btn btn-small';btn.dataset.action=dir;btn.textContent=label;exp.append(btn)}}const cats=document.createElement('div');cats.className='match-categories';for(const [cat,label] of Object.entries(labels)){const b=document.createElement('button');b.type='button';b.dataset.action='protect';b.dataset.category=cat;b.textContent=label;cats.append(b)}row.append(meta,sn,exp,cats);dom.indexList.append(row)}}
dom.indexList.addEventListener('click',e=>{const row=e.target.closest('.match-row');if(!row)return;const i=Number(row.dataset.matchIndex),a=e.target.closest('[data-action]')?.dataset.action;if(a==='focus'){state.activeMatchIndex=i;focusMatch();return}if(a==='left'||a==='right'){expand(i,a);return}if(a==='protect'){const input=row.querySelector('[data-role="expanded"]');addEntity(input.value,e.target.closest('[data-category]').dataset.category)}});
function expand(i,dir){const m=state.searchMatches[i];if(!m)return;if(dir==='left'){const x=state.rawText.slice(0,m.expandedStart).match(/\S+\s*$/u);if(x)m.expandedStart-=x[0].length}else{const x=state.rawText.slice(m.expandedEnd).match(/^\s*\S+/u);if(x)m.expandedEnd+=x[0].length}renderIndex()}
dom.searchInput.addEventListener('input',e=>{state.searchQuery=e.target.value;state.activeMatchIndex=-1;renderVisual()});dom.btnClearSearch.onclick=()=>{dom.searchInput.value='';state.searchQuery='';state.activeMatchIndex=-1;renderVisual();dom.searchInput.focus()};dom.btnPrevMatch.onclick=()=>{if(state.activeMatchIndex>0){state.activeMatchIndex--;focusMatch()}};dom.btnNextMatch.onclick=()=>{if(state.activeMatchIndex<state.searchMatches.length-1){state.activeMatchIndex++;focusMatch()}};
function selectText(){const sel=getSelection();if(!sel||sel.isCollapsed||!dom.visualEditor.contains(sel.anchorNode)||!dom.visualEditor.contains(sel.focusNode)){dom.selectionBar.hidden=true;return}const text=sel.toString().trim();if(text.length<2){dom.selectionBar.hidden=true;return}state.currentSelection=text;dom.selectionText.textContent=text.length>90?`${text.slice(0,90)}…`:text;dom.selectionBar.hidden=false}
dom.visualEditor.addEventListener('mouseup',selectText);dom.visualEditor.addEventListener('keyup',selectText);dom.selectionBar.addEventListener('click',e=>{const b=e.target.closest('[data-category]');if(b&&state.currentSelection){addEntity(state.currentSelection,b.dataset.category);getSelection()?.removeAllRanges()}});
function addEntity(text,type){const clean=text.trim();if(!clean)return;const existing=state.entities.find(e=>e.original.toLocaleLowerCase('es')===clean.toLocaleLowerCase('es'));if(existing){toast(`Ya está protegido como ${existing.token}.`);return}state.counters[type]++;const entity={id:`e_${Date.now()}_${Math.random().toString(36).slice(2,6)}`,original:clean,token:`[${type}_${state.counters[type]}]`,type};state.entities.push(entity);state.currentSelection='';dom.selectionBar.hidden=true;renderAll();toast(`${clean} → ${entity.token}`)}
function removeEntity(id){const entity=state.entities.find(e=>e.id===id);if(!entity)return;state.entities=state.entities.filter(e=>e.id!==id);renderAll();toast(`Regla ${entity.token} eliminada.`)}
dom.visualEditor.addEventListener('click',e=>{const ent=e.target.closest('.entity-mark');if(ent){removeEntity(ent.dataset.entityId);return}const search=e.target.closest('.search-mark');if(search){state.activeMatchIndex=Number(search.dataset.searchIndex);openIndex();focusMatch()}});dom.visualEditor.addEventListener('keydown',e=>{const ent=e.target.closest('.entity-mark');if(ent&&(e.key==='Enter'||e.key===' ')){e.preventDefault();removeEntity(ent.dataset.entityId)}});
function anonymized(){let text=state.rawText;for(const e of [...state.entities].sort((a,b)=>b.original.length-a.original.length))text=text.replace(entityRegex(e.original),e.token);return text}
function renderRegistry(){dom.registryBody.replaceChildren();dom.entityCountTab.textContent=state.entities.length;dom.restoreEntityCount.textContent=state.entities.length;if(!state.entities.length){const p=document.createElement('div');p.className='registry-empty';p.textContent='Todavía no has protegido ningún dato.';dom.registryBody.append(p);return}for(const e of state.entities){const row=document.createElement('div');row.className='registry-row';const token=document.createElement('code');token.textContent=e.token;const type=document.createElement('span');type.className='type-label';type.textContent=labels[e.type];const val=document.createElement('span');val.className='registry-value';val.textContent=e.original;const del=document.createElement('button');del.type='button';del.className='btn btn-small btn-danger';del.textContent='Quitar';del.dataset.entityId=e.id;row.append(token,type,val,del);dom.registryBody.append(row)}}
dom.registryBody.addEventListener('click',e=>{const b=e.target.closest('[data-entity-id]');if(b)removeEntity(b.dataset.entityId)});
function updateAction(){const text=state.rawText.trim(),n=state.entities.length;dom.btnGenerate.disabled=!(text&&n);if(!text)status(dom.protectStatus,'Empieza pegando o escribiendo un texto.');else if(!n)status(dom.protectStatus,'Texto cargado. Pasa a “Marcar datos” y protege al menos un fragmento.','warning');else status(dom.protectStatus,`<strong>${n} ${n===1?'regla activa':'reglas activas'}.</strong> Revisa las marcas antes de continuar.`,'success')}
function renderAll(){if(state.mode==='mark')renderVisual();renderRegistry();updateAction()}
async function copy(text,msg){if(!text.trim())return;try{if(navigator.clipboard&&isSecureContext)await navigator.clipboard.writeText(text);else{const x=document.createElement('textarea');x.value=text;x.style.position='fixed';x.style.opacity='0';document.body.append(x);x.select();if(!document.execCommand('copy'))throw Error();x.remove()}toast(msg)}catch{toast('No se pudo copiar automáticamente. Usa Ctrl+C.')}}
dom.btnPaste.onclick=async()=>{setMode('edit');try{if(!navigator.clipboard||!isSecureContext)throw Error();const text=await navigator.clipboard.readText();if(!text)return toast('El portapapeles no contiene texto.');dom.rawEditor.value=text;sync();toast('Texto pegado.')}catch{dom.rawEditor.focus();toast('Usa Ctrl+V en el editor.')}};
dom.btnReset.onclick=()=>{if((state.rawText.trim()||state.entities.length||dom.aiAnswer.value.trim())&&!confirm('¿Empezar una sesión nueva? Se borrarán el texto, las reglas y la respuesta restaurada.'))return;Object.assign(state,{rawText:'',entities:[],counters:{PERSONA:0,EMPRESA:0,UBICACION:0,SECRETO:0},searchQuery:'',searchMatches:[],activeMatchIndex:-1});dom.rawEditor.value=dom.searchInput.value=dom.aiAnswer.value=dom.restoredOutput.value='';dom.btnCopyRestored.disabled=true;closeIndex();setMode('edit');renderAll();toast('Sesión reiniciada.')};
function openModal(){state.lastFocused=document.activeElement;dom.anonymizedOutput.value=anonymized();dom.modalSummary.textContent=`${state.entities.length} ${state.entities.length===1?'regla aplicada':'reglas aplicadas'}. Comprueba que no quede información sensible sin sustituir.`;dom.promptModal.hidden=false;document.body.style.overflow='hidden';dom.btnCloseModal.focus()}
function closeModal(){dom.promptModal.hidden=true;document.body.style.overflow='';state.lastFocused?.focus()}
dom.btnGenerate.onclick=()=>{sync();if(state.rawText.trim()&&state.entities.length)openModal()};dom.btnCloseModal.onclick=closeModal;dom.promptModal.addEventListener('click',e=>{if(e.target===dom.promptModal)closeModal()});dom.promptModal.addEventListener('keydown',e=>{if(e.key==='Escape')return closeModal();if(e.key!=='Tab')return;const f=[...dom.promptModal.querySelectorAll('button:not(:disabled),textarea:not(:disabled)')],first=f[0],last=f.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}});dom.btnCopyPrompt.onclick=()=>copy(dom.anonymizedOutput.value,'Texto anonimizado copiado.');dom.btnGoRestore.onclick=()=>{closeModal();setPanel('restore');dom.aiAnswer.focus()};
dom.btnRestore.onclick=()=>{let text=dom.aiAnswer.value;if(!text.trim()){dom.restoredOutput.value='';dom.btnCopyRestored.disabled=true;return status(dom.restoreStatus,'Pega primero una respuesta.','warning')}if(!state.entities.length){dom.restoredOutput.value=text;dom.btnCopyRestored.disabled=false;return status(dom.restoreStatus,'No hay entidades en esta sesión.','warning')}let out=text,hits=0;for(const e of state.entities){const re=new RegExp(escapeRegExp(e.token),'gi');hits+=out.match(re)?.length||0;out=out.replace(re,e.original)}dom.restoredOutput.value=out;dom.btnCopyRestored.disabled=!out.trim();status(dom.restoreStatus,hits?`<strong>${hits} ${hits===1?'identificador restaurado':'identificadores restaurados'}.</strong> Revisa el resultado.`:'No se encontró ningún identificador conocido.','success')};
dom.btnCopyRestored.onclick=()=>copy(dom.restoredOutput.value,'Resultado copiado.');window.addEventListener('beforeunload',e=>{if(state.rawText.trim()||state.entities.length){e.preventDefault();e.returnValue=''}});renderRegistry();updateAction();
})();
