package com.soyunomas.horariolectivo;

import android.app.*;import android.appwidget.*;import android.content.*;import android.os.*;import android.view.View;import android.widget.RemoteViews;import java.time.*;import java.time.format.DateTimeFormatter;import java.util.*;import static com.soyunomas.horariolectivo.ScheduleModels.*;

public final class HorarioWidgetProvider extends AppWidgetProvider{
 static final String ACTION_REFRESH="com.soyunomas.horariolectivo.REFRESH_WIDGET";static final Locale ES=new Locale("es","ES");static final int GREEN=0xFF86EFAC,RED=0xFFFCA5A5,AMBER=0xFFFBBF24;
 @Override public void onUpdate(Context c,AppWidgetManager m,int[]ids){for(int id:ids)updateWidget(c,m,id);WidgetScheduler.schedule(c);}
 @Override public void onAppWidgetOptionsChanged(Context c,AppWidgetManager m,int id,Bundle o){super.onAppWidgetOptionsChanged(c,m,id,o);updateWidget(c,m,id);WidgetScheduler.schedule(c);}
 @Override public void onReceive(Context c,Intent i){super.onReceive(c,i);String a=i.getAction();if(ACTION_REFRESH.equals(a)||Intent.ACTION_TIME_CHANGED.equals(a)||Intent.ACTION_TIMEZONE_CHANGED.equals(a)||Intent.ACTION_DATE_CHANGED.equals(a))refreshAll(c);}
 static void refreshAll(Context c){AppWidgetManager m=AppWidgetManager.getInstance(c);int[]ids=m.getAppWidgetIds(new ComponentName(c,HorarioWidgetProvider.class));for(int id:ids)updateWidget(c,m,id);if(ids.length>0)WidgetScheduler.schedule(c);}
 static void updateWidget(Context c,AppWidgetManager m,int id){Data d=new ScheduleRepository(c).load();ZonedDateTime now=ZonedDateTime.now();NowNext nn=ScheduleEngine.findNowNext(d,now);SlotRef nextLectiva=findNextLectiva(d,now);boolean compact=isCompact(m.getAppWidgetOptions(id));RemoteViews v=new RemoteViews(c.getPackageName(),compact?R.layout.widget_horario_compact:R.layout.widget_horario);v.setTextViewText(R.id.widget_day,now.format(DateTimeFormatter.ofPattern("EEE d",ES)).toUpperCase(ES));bindCurrent(v,d,nn.current,now);bindNext(v,d,nextLectiva,now,complementaryContext(d,now,nextLectiva));Intent open=new Intent(c,MainActivity.class).addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP|Intent.FLAG_ACTIVITY_SINGLE_TOP);v.setOnClickPendingIntent(R.id.widget_root,PendingIntent.getActivity(c,0,open,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE));m.updateAppWidget(id,v);}
 static boolean isCompact(Bundle o){if(o==null)return false;int h=o.getInt(AppWidgetManager.OPTION_APPWIDGET_MAX_HEIGHT,0),min=o.getInt(AppWidgetManager.OPTION_APPWIDGET_MIN_HEIGHT,0);return(h>0&&h<100)||(h==0&&min>0&&min<80);}
 static void bindCurrent(RemoteViews v,Data d,SlotRef r,ZonedDateTime now){boolean lect=r!=null&&!r.slot.isBreak&&d.isLectiva(r.code),comp=r!=null&&!r.slot.isBreak&&d.isComplementaria(r.code);int col=lect?GREEN:comp?AMBER:RED;v.setInt(R.id.current_card,"setBackgroundResource",lect?R.drawable.widget_highlight_active:comp?R.drawable.widget_highlight_complementary:R.drawable.widget_highlight);v.setTextColor(R.id.current_label,col);v.setTextColor(R.id.current_remaining,col);if(r==null){v.setTextViewText(R.id.current_subject,"SIN CLASE");v.setTextViewText(R.id.current_time,"");v.setTextViewText(R.id.current_remaining,"");return;}v.setTextViewText(R.id.current_subject,comp?"COMPLEMENTARIA":displayCode(r));v.setTextViewText(R.id.current_time,fmt(r.slot.start)+"–"+fmt(r.slot.end));ZonedDateTime end=ZonedDateTime.of(now.toLocalDate(),r.slot.end,now.getZone());long min=(Math.max(0,Duration.between(now,end).getSeconds())+59)/60;v.setTextViewText(R.id.current_remaining,min==1?"queda 1 min":"quedan "+min+" min");}
 static void bindNext(RemoteViews v,Data d,SlotRef r,ZonedDateTime now,String ctx){v.setTextViewText(R.id.next_label,"SIGUIENTE LECTIVA");if(ctx==null){v.setViewVisibility(R.id.next_context,View.GONE);}else{v.setViewVisibility(R.id.next_context,View.VISIBLE);v.setTextViewText(R.id.next_context,"COMPLEMENTARIA ANTES · "+ctx);}if(r==null){v.setTextViewText(R.id.next_subject,"NO QUEDAN LECTIVAS HOY");v.setTextViewText(R.id.next_time,"");v.setViewVisibility(R.id.next_countdown,View.GONE);return;}v.setTextViewText(R.id.next_subject,r.code);v.setTextViewText(R.id.next_time,"Empieza "+fmt(r.slot.start));ZonedDateTime start=ZonedDateTime.of(now.toLocalDate(),r.slot.start,now.getZone());v.setViewVisibility(R.id.next_countdown,View.VISIBLE);v.setChronometer(R.id.next_countdown,SystemClock.elapsedRealtime()+Math.max(0,Duration.between(now,start).toMillis()),"en %s",true);v.setChronometerCountDown(R.id.next_countdown,true);}
 static SlotRef findNextLectiva(Data d,ZonedDateTime now){int dow=now.getDayOfWeek().getValue();if(dow<1||dow>5)return null;int day=dow-1;LocalTime t=now.toLocalTime();for(Slot s:ScheduleEngine.generateAllSlots(d)){if(s.isBreak||!s.start.isAfter(t))continue;String code=d.getAssignment(day,s.shiftId,s.sessionIndex);if(d.isLectiva(code))return new SlotRef(day,s,code);}return null;}
 static String complementaryContext(Data d,ZonedDateTime now,SlotRef next){if(next==null)return null;int day=now.getDayOfWeek().getValue()-1;LocalTime first=null,last=null;for(Slot s:ScheduleEngine.generateAllSlots(d)){if(s.isBreak||!s.start.isAfter(now.toLocalTime())||!s.start.isBefore(next.slot.start))continue;String c=d.getAssignment(day,s.shiftId,s.sessionIndex);if(d.isComplementaria(c)){if(first==null)first=s.start;last=s.end;}}return first==null?null:fmt(first)+"–"+fmt(last);}
 static String displayCode(SlotRef r){if(r.slot.isBreak)return"RECREO";return r.code==null||r.code.trim().isEmpty()?"SIN ASIGNAR":r.code;}static String fmt(LocalTime t){return String.format(Locale.US,"%02d:%02d",t.getHour(),t.getMinute());}
}
final class WidgetScheduler{static void schedule(Context c){Data d=new ScheduleRepository(c).load();ZonedDateTime now=ZonedDateTime.now();long at=Math.min(ScheduleEngine.nextBoundaryMillis(d,now),now.plusMinutes(1).withSecond(0).withNano(0).toInstant().toEpochMilli());PendingIntent p=PendingIntent.getBroadcast(c,9917,new Intent(c,HorarioWidgetProvider.class).setAction(HorarioWidgetProvider.ACTION_REFRESH),PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);AlarmManager a=(AlarmManager)c.getSystemService(Context.ALARM_SERVICE);if(a!=null){a.cancel(p);a.setAndAllowWhileIdle(AlarmManager.RTC_WAKEUP,at,p);}}}
