plugins {
    id 'com.android.application'
}

android {
    namespace 'com.soyunomas.horariolectivo'
    compileSdk 36

    defaultConfig {
        applicationId 'com.soyunomas.horariolectivo'
        minSdk 26
        targetSdk 36
        versionCode 15
        versionName '1.14'
        testInstrumentationRunner 'android.test.InstrumentationTestRunner'
    }

    buildTypes { release { minifyEnabled false; proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro' } }
    compileOptions { sourceCompatibility JavaVersion.VERSION_17; targetCompatibility JavaVersion.VERSION_17 }
    lint { abortOnError true; warningsAsErrors false }
    testOptions { unitTests.returnDefaultValues = true }
}

dependencies { testImplementation 'junit:junit:4.13.2' }
