plugins {
    id 'com.android.application'
}

android {
    namespace 'com.clemente.clementime'
    compileSdk 35

    defaultConfig {
        applicationId 'com.clemente.clementime'
        minSdk 17
        targetSdk 29
        versionCode 6
        versionName '1.5'
    }
}

// APK is rebuilt automatically by .github/workflows/build-clementime.yml
